---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: saltdocker
  pillars-from-files:
    saltdocker.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
        - saltdocker

platforms:
- name: debian
  driver_config:
    image: debian

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
          - saltdocker

verifier:
  name: shell
  remote_exec: false
  command: .venv/bin/py.test -s --connection=docker  --hosts=root@$KITCHEN_CONTAINER_ID --html=reports/$KITCHEN_INSTANCE.html --self-contained-html --junit-xml=reports/junit-$KITCHEN_INSTANCE.xml tests/integration/$KITCHEN_SUITE
